# fly.toml app configuration file generated for stocks-portfolio-wispy-breeze-9832 on 2024-02-01T22:30:13-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stocks-portfolio'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
